### ISSUE TITLE
Racks have no support for memory and ChipWait field for scripts

### ISSUE THREAD

**Issue by Avril112113** [martindevans/YololShipSystemSpec#1]
Suggestion
```yaml
networks:
  - &primary
    - !rack
      module:
        - !chip_core
          - !chip
            ChipWait: waitMagic
            script: "rack'em up.yolol"
          - !memory
            0: field0
            9: cool10
```
Link to the relevant conversation
https://discordapp.com/channels/590281942184755239/602007951170863104/675173768523415565
