### ISSUE TITLE
Spec versioning

### ISSUE THREAD

**Issue by Avril112113** [martindevans/YololShipSystemSpec#2]
Add versioning to the spec, example:
```yaml
version: "1.2.0"

networks:
  __Stuff__

relays:
  __Stuff__
```
